name: grzesbank_app
description: Grzesbank24
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  provider:
  requests:
  intl: 
  flutter:
    sdk: flutter
  google_fonts: 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/gb_logo.png"
  min_sdk_android: 20 # android min sdk min:16, default 21
  web:
    generate: true


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/card_template.jpeg
    - assets/translations.json
    - assets/gb_logo.png
    - assets/loc_pin.png
  fonts:
    - family: OCRA
      fonts:
        - asset: assets/OCR-A.woff
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
